#define DYNEventSpecial
#if !defined(FMU_SOURCE_SINGLE_UNIT) && !defined(BUILDFMU) && !defined(DYMOSIM) && !defined(STANDALONE_DYMOSIM) && !defined(Matlab6)
#define DYMOSIM
#if defined(GODESS2) && !defined(GODESS)
#define GODESS
#endif
#endif

  /* DSblock model generated by Dymola from Modelica model ModelExamples.TestModel1
 Dymola Version 2025x Refresh 1, 2025-04-11 translated this at Mon Sep  8 10:16:57 2025

   */

#include "matrixop.h"
#include "matrixop.c"
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    1
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    0
#define NWC_   0
#define NWP_   0
#define NWD_   0
#define NP_    1
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 659211281
#define NHash2_ -1579946195
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    0
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#define NSparse_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include "moutil.h"
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="ModelExamples.TestModel1";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "C:/Users/1/AppData/Roaming/DassaultSystemes/Dymola/dymola.lic";
#include "dsblock1.c"

/* Define variable names. */

#define Sections_

TranslatedEquations
InitialSection

InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(F_,0) =  -DYNX(DP_,0)*DYNX(X_,0);

AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include "dsblock6.c"

PreNonAliasNew(0)
StartNonAlias(0)
DeclareState("x", "", 0, 1, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(x)", "", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("a", "", 0, 10, 0.0,0.0,0.0,0,560)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
EndDataBlock
